/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Generate a random 32-byte Data Encryption Key (DEK) as hex */
export declare function generateDek(): string
/**
 * Encrypt plaintext using AES-256-GCM. Returns JSON { ciphertext, iv, tag } as hex.
 * Key material is zeroized after use.
 */
export declare function encryptAes256Gcm(plaintext: string, keyHex: string): string
/** Decrypt AES-256-GCM ciphertext. Key material is zeroized after use. */
export declare function decryptAes256Gcm(ciphertextHex: string, ivHex: string, tagHex: string, keyHex: string): string
/** Encrypt a DEK with a KEK (envelope encryption layer) */
export declare function wrapDek(dekHex: string, kekHex: string): string
/** Decrypt a DEK with a KEK */
export declare function unwrapDek(wrappedJson: string, kekHex: string): string
export declare function sha256Hash(input: string): string
export declare function hmacSha256Sign(message: string, secret: string): string
export declare function hmacSha256Verify(message: string, secret: string, expectedHex: string): boolean
export declare function randomBytesHex(length: number): string
