/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Store signer-service KEKs in Rust memory instead of retaining JS string fields. */
export declare function configureKeks(currentKekHex: string, previousKekHex?: string | null): void
/** Generate a random 32-byte Data Encryption Key (DEK) as raw bytes. */
export declare function generateDek(): Buffer
/**
 * Encrypt plaintext using AES-256-GCM. Returns JSON { ciphertext, iv, tag } as hex.
 * Key material is zeroized after use.
 */
export declare function encryptAes256Gcm(plaintext: string, keyHex: string): string
/**
 * Encrypt arbitrary bytes using AES-256-GCM. Returns JSON { ciphertext, iv, tag } as hex.
 * Key material is zeroized after use.
 */
export declare function encryptAes256GcmBytes(plaintext: Buffer, keyHex: string): string
/** Encrypt arbitrary bytes using a raw 32-byte key Buffer. */
export declare function encryptAes256GcmBytesWithRawKey(plaintext: Buffer, key: Buffer): string
/** Encrypt arbitrary bytes using the configured current KEK. */
export declare function encryptAes256GcmBytesWithConfiguredKek(plaintext: Buffer): string
/** Decrypt AES-256-GCM ciphertext. Key material is zeroized after use. */
export declare function decryptAes256Gcm(ciphertextHex: string, ivHex: string, tagHex: string, keyHex: string): string
/** Decrypt AES-256-GCM ciphertext as arbitrary bytes. Key material is zeroized after use. */
export declare function decryptAes256GcmBytes(ciphertextHex: string, ivHex: string, tagHex: string, keyHex: string): Buffer
/** Decrypt AES-256-GCM ciphertext as bytes using a raw 32-byte key Buffer. */
export declare function decryptAes256GcmBytesWithRawKey(ciphertextHex: string, ivHex: string, tagHex: string, key: Buffer): Buffer
/** Decrypt AES-256-GCM ciphertext as bytes using the configured current KEK. */
export declare function decryptAes256GcmBytesWithConfiguredKek(ciphertextHex: string, ivHex: string, tagHex: string): Buffer
/** Encrypt a DEK with a KEK (envelope encryption layer) */
export declare function wrapDek(dekHex: string, kekHex: string): string
/** Decrypt a DEK with a KEK */
export declare function unwrapDek(wrappedJson: string, kekHex: string): string
/** Encrypt a raw DEK Buffer with the configured current KEK. */
export declare function wrapDekWithCurrentKek(dek: Buffer): string
/** Decrypt a stored DEK using the configured current or previous KEK. */
export declare function decryptDekWithStoredKek(ciphertextHex: string, ivHex: string, tagHex: string, usePrevious: boolean): Buffer
export declare function sha256Hash(input: string): string
export declare function hmacSha256Sign(message: string, secret: string): string
export declare function hmacSha256Verify(message: string, secret: string, expectedHex: string): boolean
export declare function randomBytesHex(length: number): string
/**
 * Compute a Keccak-256 hash of the input bytes.
 * This is the hash function used by Ethereum (different from NIST SHA3-256).
 */
export declare function keccak256(input: Buffer): Buffer
/**
 * Derive an Ethereum address (20 bytes) from a secp256k1 private key (32 bytes).
 *
 * Algorithm: privateKey -> uncompressed public key (64 bytes, strip 04 prefix)
 * -> keccak256 -> take last 20 bytes.
 *
 * SECURITY: The private key bytes are held in a `Zeroizing` wrapper and are
 * wiped from Rust memory as soon as this function returns.
 */
export declare function privateKeyToEthAddress(privateKey: Buffer): Buffer
/**
 * Derive an Ethereum address from a private key supplied as the ASCII bytes of
 * a "0x"-prefixed hex string (e.g. the bytes of `"0xabcd..."`).
 *
 * This variant is used when the key is stored as a hex-encoded Buffer so the
 * raw 32-byte key material never needs to be decoded in JavaScript — all hex
 * decoding happens in Rust memory with zeroization on completion.
 */
export declare function privateKeyHexBytesToEthAddress(privateKeyHexBytes: Buffer): Buffer
/**
 * Sign a 32-byte digest where the private key is provided as the ASCII bytes
 * of a "0x"-prefixed hex string (e.g. the bytes of `"0xabcd..."`).
 *
 * This variant is used when the key is stored as a hex-encoded Buffer so the
 * raw 32-byte key material never needs to be decoded in JavaScript — all hex
 * decoding and ECDSA signing happen in Rust memory with full zeroization.
 *
 * Returns 65 bytes: [r (32) | s (32) | v (1)] (Ethereum recovery format).
 */
export declare function signSecp256K1HexKey(privateKeyHexBytes: Buffer, digest: Buffer): Buffer
/**
 * Sign a 32-byte digest using secp256k1 ECDSA (Ethereum-compatible).
 *
 * - `private_key`: exactly 32 bytes; zeroized in Rust memory after use.
 * - `digest`: exactly 32 bytes (the pre-hashed message, e.g. an EIP-712 hash).
 *
 * Returns 65 bytes: [r (32) | s (32) | v (1)], where v is 27 or 28
 * (Ethereum-style recovery ID with the +27 offset applied).
 *
 * SECURITY: The private key bytes are held in a `Zeroizing` wrapper and are
 * wiped from Rust memory as soon as this function returns.
 */
export declare function signSecp256K1(privateKey: Buffer, digest: Buffer): Buffer
