import { ApiProperty } from "@nestjs/swagger";
import { IsString, Matches } from "class-validator";

export class TotpConfirmDto {
  @ApiProperty({
    example: "123456",
    description: "6-digit TOTP code generated by the authenticator app",
  })
  @IsString()
  @Matches(/^\d{6}$/, { message: "code must be a 6-digit number" })
  code: string;
}
