import { Module, RequestMethod } from "@nestjs/common";
import { LoggerModule as PinoLoggerModule } from "nestjs-pino";

@Module({
  imports: [
    PinoLoggerModule.forRoot({
      forRoutes: [{ path: "{*path}", method: RequestMethod.ALL }],
      pinoHttp: {
        level: process.env.LOG_LEVEL ?? "info",
        transport:
          process.env.NODE_ENV === "development"
            ? {
                target: "pino-pretty",
                options: {
                  colorize: true,
                  singleLine: true,
                  translateTime: "HH:MM:ss",
                },
              }
            : undefined,
        redact: [
          "req.headers.authorization",
          "req.headers.cookie",
          'req.headers["set-cookie"]',
          'res.headers["set-cookie"]',
          "req.body.password",
          "req.body.privateKey",
          "req.body.apiSecret",
          "req.body.apiKey",
          "req.body.apiPassphrase",
          "*.token",
          "*.accessToken",
          "*.refreshToken",
          "*.apiKey",
          "*.secret",
          "*.totpSecret",
          "*.backupCode",
          "*.signature",
          "*.email",
          "req.body.email",
          "*.walletAddress",
          "req.body.walletAddress",
          "*.mnemonic",
          "req.body.mnemonic",
          "*.PAPERCLIP_API_KEY",
          "*.PAPERCLIP_COMPANY_ID",
          "*.PAPERCLIP_AGENT_ID",
          "*.PAPERCLIP_SESSION_TOKEN",
          "*.PAPERCLIP_SECRET",
          "*.PAPERCLIP_PASSWORD",
          "*.PAPERCLIP_JWT",
          "*.PAPERCLIP_JWT_TOKEN",
          "*.PAPERCLIP_ACCESS_TOKEN",
          "PAPERCLIP_API_KEY",
          "PAPERCLIP_COMPANY_ID",
          "PAPERCLIP_AGENT_ID",
          "PAPERCLIP_SESSION_TOKEN",
          "PAPERCLIP_SECRET",
          "PAPERCLIP_PASSWORD",
          "PAPERCLIP_JWT",
          "PAPERCLIP_JWT_TOKEN",
          "PAPERCLIP_ACCESS_TOKEN",
          "req.body.PAPERCLIP_API_KEY",
          "req.body.PAPERCLIP_COMPANY_ID",
          "req.body.PAPERCLIP_AGENT_ID",
          "req.body.PAPERCLIP_SESSION_TOKEN",
          "req.body.PAPERCLIP_SECRET",
          "req.body.PAPERCLIP_PASSWORD",
          "req.body.PAPERCLIP_JWT",
          "req.body.PAPERCLIP_JWT_TOKEN",
          "req.body.PAPERCLIP_ACCESS_TOKEN",
          "req.body.*.PAPERCLIP_API_KEY",
          "req.body.*.PAPERCLIP_COMPANY_ID",
          "req.body.*.PAPERCLIP_AGENT_ID",
          "req.body.*.PAPERCLIP_SESSION_TOKEN",
          "req.body.*.PAPERCLIP_SECRET",
          "req.body.*.PAPERCLIP_PASSWORD",
          "req.body.*.PAPERCLIP_JWT",
          "req.body.*.PAPERCLIP_JWT_TOKEN",
          "req.body.*.PAPERCLIP_ACCESS_TOKEN",
          "*.DEEPSEEK_API_KEY",
          "*.ANTHROPIC_API_KEY",
          "*.OPENAI_API_KEY",
          "*.GITHUB_TOKEN",
          "*.GITHUB_PAT",
          "DEEPSEEK_API_KEY",
          "ANTHROPIC_API_KEY",
          "OPENAI_API_KEY",
          "GITHUB_TOKEN",
          "GITHUB_PAT",
          "req.body.DEEPSEEK_API_KEY",
          "req.body.ANTHROPIC_API_KEY",
          "req.body.OPENAI_API_KEY",
          "req.body.GITHUB_TOKEN",
          "req.body.GITHUB_PAT",
          "req.body.*.DEEPSEEK_API_KEY",
          "req.body.*.ANTHROPIC_API_KEY",
          "req.body.*.OPENAI_API_KEY",
          "req.body.*.GITHUB_TOKEN",
          "req.body.*.GITHUB_PAT",
        ],
      },
    }),
  ],
  exports: [PinoLoggerModule],
})
export class LoggerModule {}
