-- AlterTable
ALTER TABLE "admins" ADD COLUMN IF NOT EXISTS "totpSecret" VARCHAR(255);
ALTER TABLE "admins" ADD COLUMN IF NOT EXISTS "totpEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "admins" ADD COLUMN IF NOT EXISTS "totpEnabledAt" TIMESTAMP(3);
