import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { test } from 'node:test';
import { fileURLToPath } from 'node:url';
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const apps = [{ name: 'admin-app', packagePath: 'apps/admin-app/package.json', sentryPath: 'apps/admin-app/src/lib/sentry.ts', viteConfigPath: 'apps/admin-app/vite.config.ts', errorBoundaryPath: 'apps/admin-app/src/components/error-boundary.tsx' }, { name: 'user-app', packagePath: 'apps/user-app/package.json', sentryPath: 'apps/user-app/src/lib/sentry.ts', viteConfigPath: 'apps/user-app/vite.config.ts', errorBoundaryPath: 'apps/user-app/src/components/error-boundary.tsx' }];
function readText(relativePath) { return readFileSync(resolve(repoRoot, relativePath), 'utf8'); }
function readJson(relativePath) { return JSON.parse(readText(relativePath)); }
function getLockfileImporter(lockfile, importerName) { const start = lockfile.indexOf(`  ${importerName}:\n`); assert.notEqual(start, -1, `${importerName} must exist in pnpm-lock.yaml`); const next = lockfile.slice(start + 1).search(/\n\n  [^\s][^:\n]*:\n/); return next === -1 ? lockfile.slice(start) : lockfile.slice(start, start + 1 + next); }
test('frontend apps depend on @sentry/react v10 in package manifests and lockfile importers', () => { const lockfile = readText('pnpm-lock.yaml'); for (const app of apps) { const manifest = readJson(app.packagePath); assert.match(manifest.dependencies['@sentry/react'], /^\^10\./, `${app.name} must use @sentry/react v10`); const importer = app.packagePath.replace('/package.json', ''); const lockImporter = getLockfileImporter(lockfile, importer); assert.match(lockImporter, /'@sentry\/react':\n\s+specifier: \^10\.53\.1\n\s+version: 10\.53\.1\(react@19\.2\.\d+\)/, `${app.name} lockfile importer must resolve @sentry/react 10.53.1`); } });
test('frontend Sentry wrappers keep v10-stable browser APIs and DSN drop behavior', () => { for (const app of apps) { const sentry = readText(app.sentryPath); assert.match(sentry, /import \* as Sentry from '@sentry\/react';/, `${app.name} should import the React SDK namespace`); assert.match(sentry, /Sentry\.init\(\{[\s\S]*beforeSend\(event\)/, `${app.name} should configure beforeSend`); assert.match(sentry, /if \(!SENTRY_DSN\) return null;/, `${app.name} should drop events when VITE_SENTRY_DSN is unset`); assert.match(sentry, /Sentry\.setUser\(/, `${app.name} should keep setUser instrumentation`); assert.match(sentry, /Sentry\.captureException\(/, `${app.name} should keep captureException instrumentation`); assert.doesNotMatch(sentry, /browserTracingIntegration|replayIntegration|new BrowserTracing|new Replay/, `${app.name} should not add tracing or replay integrations as part of the v10 bump`); } });
test('frontend Vite apps do not claim Sentry tunnel or source-map upload support', () => { for (const app of apps) { const viteConfig = readText(app.viteConfigPath); assert.doesNotMatch(viteConfig, /@sentry\/vite-plugin|sentryVitePlugin/, `${app.name} should not use the Sentry Vite plugin`); assert.doesNotMatch(viteConfig, /\btunnel\b/, `${app.name} should not configure a Sentry tunnel`); assert.doesNotMatch(viteConfig, /\bsourcemap\s*:\s*true\b/, `${app.name} should not emit browser source maps by default`); } });
test('frontend error boundaries still report component stacks through captureError', () => { for (const app of apps) { const boundary = readText(app.errorBoundaryPath); assert.match(boundary, /extends BaseErrorBoundary/, `${app.name} should keep the shared UI error boundary base`); assert.match(boundary, /super\.componentDidCatch\(error, errorInfo\);/, `${app.name} should preserve base handling`); assert.match(boundary, /captureError\(error, \{ componentStack: errorInfo\.componentStack \?\? undefined \}\);/, `${app.name} should report component stacks`); } });
