"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ActionsService = void 0;
const common_1 = require("@nestjs/common");
const AVAILABLE_ACTIONS = {
    version: "1.0",
    actions: [
        // ─── Markets ───────────────────────────────────────────────────────
        {
            name: "list_markets",
            description: "Browse prediction markets with optional filters",
            method: "GET",
            path: "/api/v1/markets",
            scope: "READ",
            category: "markets",
            parameters: [
                { name: "search", type: "string", required: false, in: "query", description: "Full-text search query" },
                { name: "category", type: "string", required: false, in: "query", enum: ["Sports", "Crypto", "Politics", "Economics", "Finance", "Technology"], description: "Filter by category" },
                { name: "closed", type: "boolean", required: false, in: "query", description: "Include closed markets" },
                { name: "sort", type: "string", required: false, in: "query", enum: ["volume", "endDate", "firstSeenAt"], default: "volume" },
                { name: "page", type: "number", required: false, in: "query", default: 1, min: 1 },
                { name: "limit", type: "number", required: false, in: "query", default: 20, max: 100, min: 1 },
            ],
        },
        {
            name: "get_market",
            description: "Get details for a specific market",
            method: "GET",
            path: "/api/v1/markets/:marketId",
            scope: "READ",
            category: "markets",
            parameters: [{ name: "marketId", type: "string", required: true, in: "path", description: "Market ID" }],
        },
        {
            name: "get_price_history",
            description: "Get price history for a token",
            method: "GET",
            path: "/api/v1/markets/:tokenId/price-history",
            scope: "READ",
            category: "markets",
            parameters: [
                { name: "tokenId", type: "string", required: true, in: "path", description: "Token ID" },
                { name: "resolution", type: "string", required: false, in: "query", enum: ["1m", "1h", "1d"], default: "1h" },
                { name: "from", type: "string", required: false, in: "query", description: "ISO 8601 start date" },
                { name: "to", type: "string", required: false, in: "query", description: "ISO 8601 end date" },
                { name: "limit", type: "number", required: false, in: "query", default: 200, max: 1000, min: 1 },
            ],
        },
        {
            name: "get_order_book",
            description: "Get live order book for a token",
            method: "GET",
            path: "/api/v1/markets/:tokenId/book",
            scope: "READ",
            category: "markets",
            parameters: [{ name: "tokenId", type: "string", required: true, in: "path", description: "Token ID" }],
        },
        // ─── Strategies ────────────────────────────────────────────────────
        {
            name: "list_strategies",
            description: "List your trading strategies",
            method: "GET",
            path: "/api/v1/strategies",
            scope: "READ",
            category: "strategies",
            parameters: [
                { name: "page", type: "number", required: false, in: "query", default: 1 },
                { name: "limit", type: "number", required: false, in: "query", default: 20, max: 100 },
            ],
        },
        {
            name: "create_strategy",
            description: "Create a new trading strategy",
            method: "POST",
            path: "/api/v1/strategies",
            scope: "WRITE",
            category: "strategies",
            parameters: [
                { name: "name", type: "string", required: true, in: "body", description: "Strategy name (max 100 chars)" },
                { name: "description", type: "string", required: false, in: "body", description: "Strategy description" },
                { name: "visibility", type: "string", required: false, in: "body", enum: ["PRIVATE", "PUBLIC", "UNLISTED"], default: "PRIVATE" },
                { name: "execMode", type: "string", required: false, in: "body", enum: ["EVENT", "TICK", "HYBRID"], default: "TICK" },
                { name: "tickMs", type: "number", required: false, in: "body", default: 1000, min: 200, max: 60000 },
            ],
        },
        {
            name: "get_strategy",
            description: "Get details for a specific strategy",
            method: "GET",
            path: "/api/v1/strategies/:id",
            scope: "READ",
            category: "strategies",
            parameters: [{ name: "id", type: "string", required: true, in: "path", description: "Strategy UUID" }],
        },
        {
            name: "update_strategy",
            description: "Update an existing strategy",
            method: "PATCH",
            path: "/api/v1/strategies/:id",
            scope: "WRITE",
            category: "strategies",
            parameters: [
                { name: "id", type: "string", required: true, in: "path", description: "Strategy UUID" },
                { name: "name", type: "string", required: false, in: "body" },
                { name: "description", type: "string", required: false, in: "body" },
            ],
        },
        {
            name: "delete_strategy",
            description: "Delete a strategy",
            method: "DELETE",
            path: "/api/v1/strategies/:id",
            scope: "WRITE",
            category: "strategies",
            parameters: [{ name: "id", type: "string", required: true, in: "path", description: "Strategy UUID" }],
        },
        {
            name: "start_strategy",
            description: "Start a strategy (live or paper mode)",
            method: "POST",
            path: "/api/v1/strategies/:id/start",
            scope: "TRADE",
            category: "strategies",
            parameters: [
                { name: "id", type: "string", required: true, in: "path", description: "Strategy UUID" },
                { name: "mode", type: "string", required: false, in: "body", enum: ["live", "paper"], default: "paper" },
            ],
        },
        {
            name: "stop_strategy",
            description: "Stop a running strategy",
            method: "POST",
            path: "/api/v1/strategies/:id/stop",
            scope: "TRADE",
            category: "strategies",
            parameters: [{ name: "id", type: "string", required: true, in: "path", description: "Strategy UUID" }],
        },
        {
            name: "pause_strategy",
            description: "Pause a running strategy",
            method: "POST",
            path: "/api/v1/strategies/:id/pause",
            scope: "TRADE",
            category: "strategies",
            parameters: [{ name: "id", type: "string", required: true, in: "path", description: "Strategy UUID" }],
        },
        {
            name: "resume_strategy",
            description: "Resume a paused strategy",
            method: "POST",
            path: "/api/v1/strategies/:id/resume",
            scope: "TRADE",
            category: "strategies",
            parameters: [{ name: "id", type: "string", required: true, in: "path", description: "Strategy UUID" }],
        },
        {
            name: "fork_strategy",
            description: "Fork (copy) a public strategy into your account",
            method: "POST",
            path: "/api/v1/strategies/:id/fork",
            scope: "WRITE",
            category: "strategies",
            parameters: [{ name: "id", type: "string", required: true, in: "path", description: "Strategy UUID to fork" }],
        },
        {
            name: "like_strategy",
            description: "Toggle like on a strategy",
            method: "POST",
            path: "/api/v1/strategies/:id/like",
            scope: "WRITE",
            category: "strategies",
            parameters: [{ name: "id", type: "string", required: true, in: "path", description: "Strategy UUID" }],
        },
        {
            name: "export_strategy",
            description: "Export a strategy as JSON",
            method: "GET",
            path: "/api/v1/strategies/:id/export",
            scope: "READ",
            category: "strategies",
            parameters: [{ name: "id", type: "string", required: true, in: "path", description: "Strategy UUID" }],
        },
        {
            name: "import_strategy",
            description: "Import a strategy from JSON",
            method: "POST",
            path: "/api/v1/strategies/import",
            scope: "WRITE",
            category: "strategies",
        },
        {
            name: "list_strategy_templates",
            description: "List available strategy templates",
            method: "GET",
            path: "/api/v1/strategies/templates",
            scope: "READ",
            category: "strategies",
            parameters: [
                { name: "page", type: "number", required: false, in: "query", default: 1 },
                { name: "limit", type: "number", required: false, in: "query", default: 20, max: 100 },
            ],
        },
        // ─── Orders ────────────────────────────────────────────────────────
        {
            name: "list_orders",
            description: "List your order history",
            method: "GET",
            path: "/api/v1/orders",
            scope: "READ",
            category: "orders",
            parameters: [
                { name: "status", type: "string", required: false, in: "query", description: "Filter by order status" },
                { name: "strategyId", type: "string", required: false, in: "query", description: "Filter by strategy" },
                { name: "from", type: "string", required: false, in: "query", description: "ISO 8601 start date" },
                { name: "to", type: "string", required: false, in: "query", description: "ISO 8601 end date" },
                { name: "page", type: "number", required: false, in: "query", default: 1 },
                { name: "limit", type: "number", required: false, in: "query", default: 20, max: 100 },
            ],
        },
        {
            name: "close_position",
            description: "Close a position (sell all tokens)",
            method: "POST",
            path: "/api/v1/orders/close-position",
            scope: "TRADE",
            category: "orders",
            parameters: [
                { name: "tokenId", type: "string", required: true, in: "body", description: "Token ID to close" },
            ],
        },
        {
            name: "redeem_position",
            description: "Redeem a resolved position for USDC",
            method: "POST",
            path: "/api/v1/orders/redeem",
            scope: "TRADE",
            category: "orders",
        },
        {
            name: "split_position",
            description: "Split USDC.e into Yes + No outcome tokens",
            method: "POST",
            path: "/api/v1/orders/split",
            scope: "TRADE",
            category: "orders",
            parameters: [
                { name: "tokenId", type: "string", required: true, in: "body", description: "Market condition token ID" },
                { name: "amount", type: "string", required: true, in: "body", description: "USDC amount to split" },
            ],
        },
        {
            name: "merge_position",
            description: "Merge Yes + No outcome tokens back into USDC.e",
            method: "POST",
            path: "/api/v1/orders/merge",
            scope: "TRADE",
            category: "orders",
            parameters: [
                { name: "tokenId", type: "string", required: true, in: "body", description: "Market condition token ID" },
                { name: "amount", type: "string", required: true, in: "body", description: "Token amount to merge" },
            ],
        },
        // ─── Portfolio ─────────────────────────────────────────────────────
        {
            name: "get_portfolio",
            description: "Get your portfolio summary (balances, positions)",
            method: "GET",
            path: "/api/v1/portfolio",
            scope: "READ",
            category: "portfolio",
        },
        {
            name: "get_pnl",
            description: "Get P&L chart data",
            method: "GET",
            path: "/api/v1/portfolio/pnl",
            scope: "READ",
            category: "portfolio",
            parameters: [
                { name: "period", type: "string", required: false, in: "query", enum: ["7d", "30d", "90d", "allTime"], default: "30d" },
                { name: "strategyId", type: "string", required: false, in: "query", description: "Filter by strategy" },
            ],
        },
        // ─── Alerts ────────────────────────────────────────────────────────
        {
            name: "list_alerts",
            description: "List your price alerts",
            method: "GET",
            path: "/api/v1/alerts",
            scope: "READ",
            category: "alerts",
        },
        {
            name: "create_alert",
            description: "Create a new price alert",
            method: "POST",
            path: "/api/v1/alerts",
            scope: "WRITE",
            category: "alerts",
            parameters: [
                { name: "tokenId", type: "string", required: true, in: "body", description: "Token to watch" },
                { name: "direction", type: "string", required: true, in: "body", enum: ["above", "below"] },
                { name: "price", type: "string", required: true, in: "body", description: "Trigger price" },
                { name: "persistent", type: "boolean", required: false, in: "body", default: false, description: "Re-arm after triggering" },
            ],
        },
        {
            name: "delete_alert",
            description: "Delete a price alert",
            method: "DELETE",
            path: "/api/v1/alerts/:id",
            scope: "WRITE",
            category: "alerts",
            parameters: [{ name: "id", type: "string", required: true, in: "path", description: "Alert UUID" }],
        },
        // ─── Backtests ─────────────────────────────────────────────────────
        {
            name: "list_backtests",
            description: "List your backtest runs",
            method: "GET",
            path: "/api/v1/backtests",
            scope: "READ",
            category: "backtests",
            parameters: [
                { name: "strategyId", type: "string", required: false, in: "query" },
                { name: "status", type: "string", required: false, in: "query" },
                { name: "page", type: "number", required: false, in: "query", default: 1 },
                { name: "limit", type: "number", required: false, in: "query", default: 20, max: 100 },
            ],
        },
        {
            name: "create_backtest",
            description: "Run a new backtest on a strategy",
            method: "POST",
            path: "/api/v1/backtests",
            scope: "WRITE",
            category: "backtests",
            parameters: [
                { name: "strategyId", type: "string", required: true, in: "body", description: "Strategy UUID" },
            ],
        },
        {
            name: "quick_backtest",
            description: "Run a quick backtest (faster, less data)",
            method: "POST",
            path: "/api/v1/backtests/quick",
            scope: "WRITE",
            category: "backtests",
        },
        {
            name: "get_backtest",
            description: "Get backtest result details",
            method: "GET",
            path: "/api/v1/backtests/:id",
            scope: "READ",
            category: "backtests",
            parameters: [{ name: "id", type: "string", required: true, in: "path", description: "Backtest UUID" }],
        },
        // ─── Whales ────────────────────────────────────────────────────────
        {
            name: "whale_feed",
            description: "Get live whale activity feed",
            method: "GET",
            path: "/api/v1/whales/feed",
            scope: "READ",
            category: "whales",
            parameters: [
                { name: "page", type: "number", required: false, in: "query", default: 1 },
                { name: "limit", type: "number", required: false, in: "query", default: 20, max: 100 },
            ],
        },
        {
            name: "whale_top",
            description: "Get top whale traders",
            method: "GET",
            path: "/api/v1/whales/top",
            scope: "READ",
            category: "whales",
        },
        {
            name: "whale_following",
            description: "List whales you follow",
            method: "GET",
            path: "/api/v1/whales/following",
            scope: "READ",
            category: "whales",
        },
        {
            name: "whale_profile",
            description: "Get a whale trader profile by address",
            method: "GET",
            path: "/api/v1/whales/:address",
            scope: "READ",
            category: "whales",
            parameters: [{ name: "address", type: "string", required: true, in: "path", description: "Wallet address" }],
        },
        {
            name: "whale_toggle_follow",
            description: "Follow or unfollow a whale trader",
            method: "POST",
            path: "/api/v1/whales/:address/follow",
            scope: "WRITE",
            category: "whales",
            parameters: [{ name: "address", type: "string", required: true, in: "path", description: "Wallet address" }],
        },
        // ─── Copy Trading ──────────────────────────────────────────────────
        {
            name: "create_copy",
            description: "Start copy-trading a strategy",
            method: "POST",
            path: "/api/v1/copy",
            scope: "TRADE",
            category: "copy",
            parameters: [
                { name: "strategyId", type: "string", required: true, in: "body", description: "Strategy UUID to copy" },
            ],
        },
        {
            name: "list_copies",
            description: "List your active copy-trading subscriptions",
            method: "GET",
            path: "/api/v1/copy",
            scope: "READ",
            category: "copy",
        },
        {
            name: "get_copy",
            description: "Get copy-trading subscription details",
            method: "GET",
            path: "/api/v1/copy/:id",
            scope: "READ",
            category: "copy",
            parameters: [{ name: "id", type: "string", required: true, in: "path" }],
        },
        {
            name: "update_copy",
            description: "Update copy-trading settings",
            method: "PATCH",
            path: "/api/v1/copy/:id",
            scope: "WRITE",
            category: "copy",
            parameters: [{ name: "id", type: "string", required: true, in: "path" }],
        },
        {
            name: "pause_copy",
            description: "Pause a copy-trading subscription",
            method: "POST",
            path: "/api/v1/copy/:id/pause",
            scope: "TRADE",
            category: "copy",
            parameters: [{ name: "id", type: "string", required: true, in: "path" }],
        },
        {
            name: "resume_copy",
            description: "Resume a paused copy-trading subscription",
            method: "POST",
            path: "/api/v1/copy/:id/resume",
            scope: "TRADE",
            category: "copy",
            parameters: [{ name: "id", type: "string", required: true, in: "path" }],
        },
        {
            name: "stop_copy",
            description: "Stop and remove a copy-trading subscription",
            method: "DELETE",
            path: "/api/v1/copy/:id",
            scope: "TRADE",
            category: "copy",
            parameters: [{ name: "id", type: "string", required: true, in: "path" }],
        },
        {
            name: "list_copy_trades",
            description: "List trades from a copy-trading subscription",
            method: "GET",
            path: "/api/v1/copy/:id/trades",
            scope: "READ",
            category: "copy",
            parameters: [
                { name: "id", type: "string", required: true, in: "path" },
                { name: "page", type: "number", required: false, in: "query", default: 1 },
                { name: "limit", type: "number", required: false, in: "query", default: 20, max: 100 },
            ],
        },
        // ─── News ──────────────────────────────────────────────────────────
        {
            name: "list_news",
            description: "Get latest news articles relevant to markets",
            method: "GET",
            path: "/api/v1/news",
            scope: "READ",
            category: "news",
        },
        {
            name: "news_signals",
            description: "Get AI-generated news signals for trading",
            method: "GET",
            path: "/api/v1/news/signals",
            scope: "READ",
            category: "news",
        },
        {
            name: "get_article",
            description: "Get a specific news article",
            method: "GET",
            path: "/api/v1/news/:id",
            scope: "READ",
            category: "news",
            parameters: [{ name: "id", type: "string", required: true, in: "path", description: "Article ID" }],
        },
        // ─── Scores ────────────────────────────────────────────────────────
        {
            name: "get_my_score",
            description: "Get your trader reputation score",
            method: "GET",
            path: "/api/v1/scores/me",
            scope: "READ",
            category: "scores",
        },
        {
            name: "get_top_traders",
            description: "Get the leaderboard of top traders by score",
            method: "GET",
            path: "/api/v1/scores/top",
            scope: "READ",
            category: "scores",
        },
        {
            name: "get_my_badges",
            description: "Get your earned badges",
            method: "GET",
            path: "/api/v1/scores/me/badges",
            scope: "READ",
            category: "scores",
        },
        // ─── Discover ──────────────────────────────────────────────────────
        {
            name: "discover_strategies",
            description: "Browse public strategies on the discover page",
            method: "GET",
            path: "/api/v1/discover",
            scope: "READ",
            category: "discover",
            parameters: [
                { name: "sort", type: "string", required: false, in: "query", enum: ["popular", "newest", "top_pnl", "most_forked"], default: "popular" },
                { name: "category", type: "string", required: false, in: "query" },
                { name: "page", type: "number", required: false, in: "query", default: 1 },
                { name: "limit", type: "number", required: false, in: "query", default: 20, max: 100 },
            ],
        },
        {
            name: "get_leaderboard",
            description: "Get the trader leaderboard",
            method: "GET",
            path: "/api/v1/leaderboard",
            scope: "READ",
            category: "discover",
            parameters: [
                { name: "period", type: "string", required: false, in: "query", enum: ["7d", "30d", "allTime"], default: "30d" },
                { name: "page", type: "number", required: false, in: "query", default: 1 },
                { name: "limit", type: "number", required: false, in: "query", default: 20, max: 100 },
            ],
        },
        // ─── Paper Trading ─────────────────────────────────────────────────
        {
            name: "paper_summary",
            description: "Get paper trading account summary",
            method: "GET",
            path: "/api/v1/paper/summary",
            scope: "READ",
            category: "paper",
        },
        {
            name: "paper_reset",
            description: "Reset your paper trading account",
            method: "POST",
            path: "/api/v1/paper/reset",
            scope: "WRITE",
            category: "paper",
        },
        // ─── Profile ───────────────────────────────────────────────────────
        {
            name: "get_profile",
            description: "View a user profile",
            method: "GET",
            path: "/api/v1/profile/:username",
            scope: "READ",
            category: "profile",
            parameters: [{ name: "username", type: "string", required: true, in: "path" }],
        },
        {
            name: "toggle_follow_user",
            description: "Follow or unfollow a user",
            method: "POST",
            path: "/api/v1/profile/:username/follow",
            scope: "WRITE",
            category: "profile",
            parameters: [{ name: "username", type: "string", required: true, in: "path" }],
        },
        // ─── Settings ──────────────────────────────────────────────────────
        {
            name: "update_profile_settings",
            description: "Update profile settings (display name, bio, etc.)",
            method: "PATCH",
            path: "/api/v1/settings/profile",
            scope: "WRITE",
            category: "settings",
        },
        {
            name: "update_notifications",
            description: "Update notification preferences",
            method: "PATCH",
            path: "/api/v1/settings/notifications",
            scope: "WRITE",
            category: "settings",
        },
        {
            name: "get_gas_usage",
            description: "Get your gas usage statistics",
            method: "GET",
            path: "/api/v1/settings/gas",
            scope: "READ",
            category: "settings",
        },
        // ─── Batch ─────────────────────────────────────────────────────────
        {
            name: "batch_execute",
            description: "Execute up to 10 API requests in a single call",
            method: "POST",
            path: "/api/v1/batch",
            scope: "READ",
            category: "batch",
            parameters: [
                {
                    name: "items",
                    type: "array",
                    required: true,
                    in: "body",
                    description: "Array of 1-10 requests, each with id, method, path, and optional body",
                },
            ],
        },
    ],
};
let ActionsService = class ActionsService {
    getActions() {
        return AVAILABLE_ACTIONS;
    }
};
exports.ActionsService = ActionsService;
exports.ActionsService = ActionsService = __decorate([
    (0, common_1.Injectable)()
], ActionsService);
//# sourceMappingURL=actions.service.js.map