#!/usr/bin/env bash
# ─── Polyforge: Fetch Secrets from AWS Secrets Manager ───────────────────────
#
# Runs on EC2 startup (via user-data or systemd) to populate .env.prod.
# Requires the EC2 IAM role to have secretsmanager:GetSecretValue on:
#   - polyforge/prod/secrets  (all app secrets)
#   - polyforge/prod/db       (RDS connection strings)
#
# The resulting .env.prod is:
#   - Written to /opt/polyforge/.env.prod
#   - Owned by root, readable only by the deploy user (chmod 640)
#   - Never committed or logged
#
# Usage:
#   sudo bash scripts/fetch-secrets.sh [--region us-east-1]

set -euo pipefail

REGION="${AWS_REGION:-us-east-1}"
SECRET_NAME_APP="polyforge/prod/secrets"
SECRET_NAME_DB="polyforge/prod/db"
OUTPUT_FILE="/opt/polyforge/.env.prod"
DEPLOY_USER="${DEPLOY_USER:-ec2-user}"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --region) REGION="$2"; shift 2 ;;
        *)        echo "Unknown arg: $1"; exit 1 ;;
    esac
done

log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }

log "Fetching secrets from AWS Secrets Manager (region: $REGION)"

# ── Require AWS CLI ───────────────────────────────────────────────────────────

if ! command -v aws &>/dev/null; then
    log "ERROR: aws CLI not found — install it first"
    exit 1
fi

if ! command -v jq &>/dev/null; then
    log "ERROR: jq not found — install it first"
    exit 1
fi

# ── Create output directory ───────────────────────────────────────────────────

mkdir -p "$(dirname "$OUTPUT_FILE")"
# Write with restricted permissions from the start
touch "$OUTPUT_FILE"
chmod 640 "$OUTPUT_FILE"
chown "root:$DEPLOY_USER" "$OUTPUT_FILE" 2>/dev/null || true

# ── Fetch and write secrets ───────────────────────────────────────────────────

write_env() {
    local secret_name="$1"
    log "Fetching secret: $secret_name"

    local json
    json=$(aws secretsmanager get-secret-value \
        --region "$REGION" \
        --secret-id "$secret_name" \
        --query SecretString \
        --output text 2>&1) || {
        log "ERROR: Failed to fetch $secret_name — $json"
        exit 1
    }

    # Convert JSON key/value object to KEY=VALUE lines, appending to output file
    echo "$json" | jq -r 'to_entries[] | "\(.key)=\(.value)"' >> "$OUTPUT_FILE"
}

# Start fresh
cat > "$OUTPUT_FILE" << 'HEADER'
# Auto-generated by fetch-secrets.sh — DO NOT EDIT MANUALLY
# Regenerate with: sudo bash scripts/fetch-secrets.sh
# Generated at: PLACEHOLDER_TIMESTAMP
NODE_ENV=production
LOG_LEVEL=info
HEADER
# Replace timestamp placeholder
sed -i "s/PLACEHOLDER_TIMESTAMP/$(date -u +%Y-%m-%dT%H:%M:%SZ)/" "$OUTPUT_FILE"

# Fetch app secrets (JWT secrets, encryption keys, builder creds, bot tokens, etc.)
write_env "$SECRET_NAME_APP"

# Fetch DB connection strings (RDS + ElastiCache URLs)
write_env "$SECRET_NAME_DB"

# ── Inject non-secret static config ──────────────────────────────────────────

cat >> "$OUTPUT_FILE" << 'EOF'

# ── Static config (non-secret) ────────────────────────────────────────────────
CHAIN_ID=137
EMAIL_DRIVER=ses
AWS_SES_FROM_EMAIL=noreply@polyforge.app
FRONTEND_URL=https://polyforge.app
ADMIN_URL=https://admin.polyforge.app
CORS_ORIGINS=https://polyforge.app
ADMIN_CORS_ORIGINS=https://admin.polyforge.app

# ── Real Polymarket API endpoints ─────────────────────────────────────────────
GAMMA_API_URL=https://gamma-api.polymarket.com
CLOB_API_URL=https://clob.polymarket.com
CLOB_WS_URL=wss://ws-subscriptions-clob.polymarket.com
DATA_API_URL=https://data-api.polymarket.com

# ── PgBouncer connection strings (services connect through pgbouncer on internal network) ──
# DATABASE_URL uses pgbouncer — overrides the direct RDS URL from Secrets Manager
EOF

# DATABASE_URL via PgBouncer (the direct URL comes from Secrets Manager as DATABASE_DIRECT_URL)
DIRECT_URL=$(grep "^DATABASE_DIRECT_URL=" "$OUTPUT_FILE" | cut -d= -f2-)
if [[ -n "$DIRECT_URL" ]]; then
    # Parse host/port/db from DIRECT_URL and rewrite for PgBouncer
    PG_HOST=$(echo "$DIRECT_URL" | sed 's|.*@\(.*\):\([0-9]*\)/.*|\1|')
    PG_PORT=$(echo "$DIRECT_URL" | sed 's|.*@.*:\([0-9]*\)/.*|\1|')
    PG_DB=$(echo "$DIRECT_URL" | sed 's|.*/\(.*\)$|\1|')
    PG_USER=$(echo "$DIRECT_URL" | sed 's|.*://\([^:]*\):.*|\1|')
    PG_PASS=$(echo "$DIRECT_URL" | sed 's|.*://[^:]*:\([^@]*\)@.*|\1|')
    echo "DATABASE_URL=postgresql://${PG_USER}:${PG_PASS}@pgbouncer:5432/${PG_DB}?pgbouncer=true&connection_limit=1" >> "$OUTPUT_FILE"
fi

ADMIN_DIRECT_URL=$(grep "^ADMIN_DATABASE_DIRECT_URL=" "$OUTPUT_FILE" | cut -d= -f2-)
if [[ -n "$ADMIN_DIRECT_URL" ]]; then
    APG_USER=$(echo "$ADMIN_DIRECT_URL" | sed 's|.*://\([^:]*\):.*|\1|')
    APG_PASS=$(echo "$ADMIN_DIRECT_URL" | sed 's|.*://[^:]*:\([^@]*\)@.*|\1|')
    APG_DB=$(echo "$ADMIN_DIRECT_URL" | sed 's|.*/\(.*\)$|\1|')
    echo "ADMIN_DATABASE_URL=postgresql://${APG_USER}:${APG_PASS}@pgbouncer-admin:5432/${APG_DB}?pgbouncer=true&connection_limit=1" >> "$OUTPUT_FILE"
fi

chmod 640 "$OUTPUT_FILE"
log "Secrets written to $OUTPUT_FILE ($(wc -l < "$OUTPUT_FILE") lines)"
log "Done."

# ─────────────────────────────────────────────────────────────────────────────
# Expected Secrets Manager layout
# ─────────────────────────────────────────────────────────────────────────────
#
# Secret: polyforge/prod/secrets  (JSON object)
# {
#   "USER_JWT_SECRET":           "<64+ char random>",
#   "ADMIN_JWT_SECRET":          "<64+ char random>",
#   "BOT_JWT_SECRET":            "<64+ char random>",
#   "INTERNAL_JWT_SECRET":       "<64+ char random>",
#   "MASTER_ENCRYPTION_KEY":     "<64 hex chars (32 bytes)>",
#   "TOTP_ENCRYPTION_KEY":       "<64 hex chars (32 bytes)>",
#   "POLY_BUILDER_API_KEY":      "<from Polymarket Builder Program>",
#   "POLY_BUILDER_SECRET":       "<from Polymarket Builder Program>",
#   "POLY_BUILDER_PASSPHRASE":   "<from Polymarket Builder Program>",
#   "BUILDER_TIER":              "UNVERIFIED",
#   "TELEGRAM_BOT_TOKEN":        "<from @BotFather>",
#   "DISCORD_BOT_TOKEN":         "<from Discord developer portal>",
#   "WHATSAPP_TOKEN":            "<from Meta Business Platform>",
#   "WHATSAPP_PHONE_ID":         "<from Meta WhatsApp Business>",
#   "WHATSAPP_VERIFY_TOKEN":     "<random string for webhook verification>",
#   "WHATSAPP_APP_SECRET":       "<Meta app secret for X-Hub-Signature-256>",
#   "ANTHROPIC_API_KEY":         "<Claude API key for NL query + strategy-from-description>",
#   "OPENAI_API_KEY":            "<OpenAI API key for NL query + strategy-from-description>",
#   "NEWS_RSS_FEEDS":            "https://feeds.reuters.com/reuters/topNews",
#   "GEO_BLOCKED_COUNTRIES":     "US,AU,BE,BY,BI,CF,CG,CU,DE,ET,FR,GB,IR,IQ,IT,KP,LB,LY,MM,NI,NL,RU,SO,SS,SD,SY,VE,YE,ZW,UM",
#   "GEO_CLOSE_ONLY_COUNTRIES":  "PL,SG,TH,TW",
#   "AWS_SES_REGION":            "us-east-1",
#   "ECR_REGISTRY":              "<account-id>.dkr.ecr.us-east-1.amazonaws.com"
# }
#
# Secret: polyforge/prod/db  (JSON object)
# {
#   "DATABASE_DIRECT_URL":       "postgresql://poly:<pass>@<rds-host>:5432/polyforge",
#   "ADMIN_DATABASE_DIRECT_URL": "postgresql://poly_admin:<pass>@<rds-host>:5432/polyforge_admin",
#   "REDIS_URL":                 "rediss://:<pass>@<elasticache-host>:6379/0"
# }
