#!/usr/bin/env bash
# ─── Polyforge: Write .env from CI-injected GitHub Secrets ───────────────────
#
# Called during the deploy-dev CI job via SSH (appleboy/ssh-action).
# All variable values come from the CI environment — never hardcoded here.
#
# Required env vars (injected by GitHub Actions, see .github/workflows/ci.yml):
#   USER_JWT_SECRET, ADMIN_JWT_SECRET, BOT_JWT_SECRET, INTERNAL_JWT_SECRET
#   MASTER_ENCRYPTION_KEY, TOTP_ENCRYPTION_KEY
#   DB_PASSWORD, ADMIN_DB_PASSWORD, REDIS_PASSWORD
#   POLY_BUILDER_API_KEY, POLY_BUILDER_SECRET, POLY_BUILDER_PASSPHRASE
#
# Optional env vars (use placeholder/disabled defaults when not supplied):
#   TELEGRAM_BOT_TOKEN, DISCORD_BOT_TOKEN
#   WHATSAPP_TOKEN, WHATSAPP_PHONE_ID, WHATSAPP_VERIFY_TOKEN, WHATSAPP_APP_SECRET
#   GAS_SPONSOR_PRIVATE_KEY, GAS_SPONSOR_ENABLED
#   ANTHROPIC_API_KEY, OPENAI_API_KEY
#
# Usage:
#   Called automatically by CI — do not run manually unless testing locally.
#   For local testing: export the variables then run: bash scripts/write-env-from-ci.sh
#
# Architecture note:
#   Dev deployment  → GitHub Secrets (this script)
#   Prod EC2        → AWS Secrets Manager (see scripts/fetch-secrets.sh)

set -euo pipefail

REPO_DIR="${REPO_DIR:-$HOME/PolyForge}"
ENV_FILE="$REPO_DIR/.env"
TMPFILE="$(mktemp "$REPO_DIR/.env.tmp.XXXXXX")"

log() { echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] $*"; }

# Validate all required secrets are present before touching .env
: "${USER_JWT_SECRET:?USER_JWT_SECRET is required}"
: "${ADMIN_JWT_SECRET:?ADMIN_JWT_SECRET is required}"
: "${BOT_JWT_SECRET:?BOT_JWT_SECRET is required}"
: "${INTERNAL_JWT_SECRET:?INTERNAL_JWT_SECRET is required}"
: "${MASTER_ENCRYPTION_KEY:?MASTER_ENCRYPTION_KEY is required}"
: "${TOTP_ENCRYPTION_KEY:?TOTP_ENCRYPTION_KEY is required}"
: "${DB_PASSWORD:?DB_PASSWORD is required}"
: "${ADMIN_DB_PASSWORD:?ADMIN_DB_PASSWORD is required}"
: "${REDIS_PASSWORD:?REDIS_PASSWORD is required}"
: "${POLY_BUILDER_API_KEY:?POLY_BUILDER_API_KEY is required}"
: "${POLY_BUILDER_SECRET:?POLY_BUILDER_SECRET is required}"
: "${POLY_BUILDER_PASSPHRASE:?POLY_BUILDER_PASSPHRASE is required}"

log "All required secrets present — writing $ENV_FILE"

# Write to temp file first (atomic replace prevents partial .env on failure)
cat > "$TMPFILE" << ENV_HEREDOC
# Auto-generated by CI from GitHub Secrets — DO NOT EDIT MANUALLY
# Source: .github/workflows/ci.yml → write-env-from-ci.sh
# Generated at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
# For local dev, copy .env.dev instead: cp .env.dev .env

# ─────────────────────────────────────────────────────────────────────────────
# RUNTIME
# ─────────────────────────────────────────────────────────────────────────────

NODE_ENV=development
LOG_LEVEL=info
ENABLE_SWAGGER=false

# ─────────────────────────────────────────────────────────────────────────────
# JWT SECRETS
# ─────────────────────────────────────────────────────────────────────────────

USER_JWT_SECRET=${USER_JWT_SECRET}
ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
BOT_JWT_SECRET=${BOT_JWT_SECRET}
INTERNAL_JWT_SECRET=${INTERNAL_JWT_SECRET}

# ─────────────────────────────────────────────────────────────────────────────
# ENCRYPTION KEYS
# ─────────────────────────────────────────────────────────────────────────────

MASTER_ENCRYPTION_KEY=${MASTER_ENCRYPTION_KEY}
MASTER_ENCRYPTION_KEY_VERSION=1
TOTP_ENCRYPTION_KEY=${TOTP_ENCRYPTION_KEY}

# ─────────────────────────────────────────────────────────────────────────────
# USER DATABASE
# POSTGRES_* vars needed by postgres container initialisation and pgbouncer
# ─────────────────────────────────────────────────────────────────────────────

POSTGRES_USER=poly
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=polyforge
DATABASE_URL=postgresql://poly:${DB_PASSWORD}@pgbouncer:5432/polyforge?pgbouncer=true&connection_limit=1
DIRECT_DATABASE_URL=postgresql://poly:${DB_PASSWORD}@postgres:5432/polyforge

# ─────────────────────────────────────────────────────────────────────────────
# ADMIN DATABASE
# ─────────────────────────────────────────────────────────────────────────────

POSTGRES_ADMIN_USER=poly_admin
POSTGRES_ADMIN_PASSWORD=${ADMIN_DB_PASSWORD}
POSTGRES_ADMIN_DB=polyforge_admin
ADMIN_DATABASE_URL=postgresql://poly_admin:${ADMIN_DB_PASSWORD}@pgbouncer-admin:5433/polyforge_admin?pgbouncer=true&connection_limit=1
ADMIN_DIRECT_DATABASE_URL=postgresql://poly_admin:${ADMIN_DB_PASSWORD}@postgres-admin:5434/polyforge_admin

# ─────────────────────────────────────────────────────────────────────────────
# REDIS
# ─────────────────────────────────────────────────────────────────────────────

REDIS_PASSWORD=${REDIS_PASSWORD}
REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379

# ─────────────────────────────────────────────────────────────────────────────
# EMAIL — mailhog for dev deployment
# ─────────────────────────────────────────────────────────────────────────────

EMAIL_DRIVER=mailhog
MAILHOG_HOST=mailhog
MAILHOG_PORT=1025
AWS_SES_REGION=us-east-1
AWS_SES_FROM_EMAIL=noreply@polyforge.app

# ─────────────────────────────────────────────────────────────────────────────
# POLYMARKET APIs — real endpoints (no mock for order execution in dev)
# mock-polymarket stays in docker-compose.infra.yml for E2E tests only
# ─────────────────────────────────────────────────────────────────────────────

GAMMA_API_URL=https://gamma-api.polymarket.com
CLOB_API_URL=https://clob.polymarket.com
CLOB_WS_URL=wss://ws-subscriptions-clob.polymarket.com/ws/market
DATA_API_URL=https://data-api.polymarket.com
SCENARIO=normal

# ─────────────────────────────────────────────────────────────────────────────
# POLYMARKET BUILDER PROGRAM
# ─────────────────────────────────────────────────────────────────────────────

POLY_BUILDER_API_KEY=${POLY_BUILDER_API_KEY}
POLY_BUILDER_SECRET=${POLY_BUILDER_SECRET}
POLY_BUILDER_PASSPHRASE=${POLY_BUILDER_PASSPHRASE}
BUILDER_TIER=UNVERIFIED

# ─────────────────────────────────────────────────────────────────────────────
# BLOCKCHAIN
# ─────────────────────────────────────────────────────────────────────────────

CHAIN_ID=137

# ─────────────────────────────────────────────────────────────────────────────
# GAS SPONSORSHIP
# ─────────────────────────────────────────────────────────────────────────────

GAS_SPONSOR_PRIVATE_KEY=${GAS_SPONSOR_PRIVATE_KEY:-}
GAS_SPONSOR_ENABLED=false
GAS_DAILY_LIMIT_MATIC=0.5
GAS_ESTIMATE_MATIC=0.002

# ─────────────────────────────────────────────────────────────────────────────
# AI NEWS PIPELINE
# ─────────────────────────────────────────────────────────────────────────────

ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
NEWS_RSS_FEEDS=https://feeds.reuters.com/reuters/topNews,https://rss.cnn.com/rss/money_latest.rss

# ─────────────────────────────────────────────────────────────────────────────
# BOTS
# ─────────────────────────────────────────────────────────────────────────────

TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-dev-disabled}
DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN:-dev-disabled}
WHATSAPP_TOKEN=${WHATSAPP_TOKEN:-dev-disabled}
WHATSAPP_PHONE_ID=${WHATSAPP_PHONE_ID:-}
WHATSAPP_VERIFY_TOKEN=${WHATSAPP_VERIFY_TOKEN:-}
WHATSAPP_APP_SECRET=${WHATSAPP_APP_SECRET:-}

# ─────────────────────────────────────────────────────────────────────────────
# GEOBLOCKING
# ─────────────────────────────────────────────────────────────────────────────

GEO_BLOCKED_COUNTRIES=US,AU,BE,BY,BI,CF,CG,CU,DE,ET,FR,GB,IR,IQ,IT,KP,LB,LY,MM,NI,NL,RU,SO,SS,SD,SY,VE,YE,ZW,UM
GEO_CLOSE_ONLY_COUNTRIES=PL,SG,TH,TW

# ─────────────────────────────────────────────────────────────────────────────
# CORS & DOMAINS
# ─────────────────────────────────────────────────────────────────────────────

FRONTEND_URL=https://localhost
ADMIN_URL=https://admin.polyforge.app
CORS_ORIGINS=https://localhost
ADMIN_CORS_ORIGINS=https://admin.polyforge.app
ADMIN_ALLOWED_IPS=

# ─────────────────────────────────────────────────────────────────────────────
# LAUNCH FLAGS
# ─────────────────────────────────────────────────────────────────────────────

INVITE_ONLY=false
COOKIE_SECURE=false

# ─────────────────────────────────────────────────────────────────────────────
# SERVICE PORTS (internal Docker network — no need to change)
# ─────────────────────────────────────────────────────────────────────────────

AUTH_SERVICE_PORT=3001
API_SERVICE_PORT=3002
ADMIN_AUTH_SERVICE_PORT=3003
ADMIN_API_SERVICE_PORT=3004
MARKET_DATA_SERVICE_PORT=3005
STRATEGY_ENGINE_PORT=3006
ORDER_SERVICE_PORT=3007
PAPER_ORDER_SERVICE_PORT=3008
BACKTEST_SERVICE_PORT=3009
NOTIFICATION_SERVICE_PORT=3010
BOT_SERVICE_PORT=3011
SIGNER_SERVICE_PORT=3012
MOCK_POLYMARKET_PORT=3096
ENV_HEREDOC

chmod 600 "$TMPFILE"
mv "$TMPFILE" "$ENV_FILE"
log "Wrote $ENV_FILE ($(wc -l < "$ENV_FILE") lines)"
log "NODE_ENV=$(grep '^NODE_ENV=' "$ENV_FILE" | cut -d= -f2)"
log "CLOB_API_URL=$(grep '^CLOB_API_URL=' "$ENV_FILE" | cut -d= -f2)"
