"""Polyforge Python SDK — typed REST client for the Polyforge trading platform."""

from polyforge.client import AsyncPolyforgeClient, PolyforgeClient
from polyforge.errors import (
    AuthenticationError,
    NotFoundError,
    PermissionError,
    PolyforgeError,
    RateLimitError,
    ServerError,
)
from polyforge.models import (
    AiQueryResponse,
    Alert,
    ConditionalOrder,
    CopyConfig,
    Market,
    MarketplaceListing,
    MarketplaceSeller,
    MarketplaceStrategy,
    NewsSignal,
    Order,
    OrderBook,
    OrderBookLevel,
    OrderStatus,
    PaginatedResponse,
    PaperSummary,
    PlaceOrderResponse,
    Portfolio,
    PortfolioPnl,
    Position,
    PriceHistoryEntry,
    Strategy,
    StrategyBlock,
    StrategyEvent,
    StrategyExecMode,
    StrategyStatusResponse,
    StrategyTemplate,
    StrategyVisibility,
    Token,
    TraderScore,
    WatchlistItem,
    Webhook,
    WebhookTestResult,
    WhaleProfile,
    WhaleTrade,
)

__all__ = [
    # Clients
    "PolyforgeClient",
    "AsyncPolyforgeClient",
    # Errors
    "PolyforgeError",
    "AuthenticationError",
    "PermissionError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    # Enums
    "OrderStatus",
    "StrategyVisibility",
    "StrategyExecMode",
    # Models
    "AiQueryResponse",
    "Alert",
    "ConditionalOrder",
    "CopyConfig",
    "Market",
    "MarketplaceListing",
    "MarketplaceSeller",
    "MarketplaceStrategy",
    "NewsSignal",
    "Order",
    "OrderBook",
    "OrderBookLevel",
    "PaginatedResponse",
    "PlaceOrderResponse",
    "Portfolio",
    "PortfolioPnl",
    "Position",
    "PriceHistoryEntry",
    "Strategy",
    "StrategyBlock",
    "StrategyEvent",
    "StrategyStatusResponse",
    "StrategyTemplate",
    "Token",
    "TraderScore",
    "PaperSummary",
    "WatchlistItem",
    "Webhook",
    "WebhookTestResult",
    "WhaleProfile",
    "WhaleTrade",
]

__version__ = "1.0.0"
