"""Polyforge Python SDK — typed REST client for the Polyforge trading platform."""

from polyforge.client import AsyncPolyforgeClient, PolyforgeClient
from polyforge.errors import (
    AuthenticationError,
    NotFoundError,
    PermissionError,
    PolyforgeError,
    RateLimitError,
    ServerError,
)
from polyforge.models import (
    AiQueryResponse,
    Alert,
    Badge,
    BatchOrderItem,
    BatchOrderResult,
    BulkCancelError,
    BulkCancelResult,
    ClobBook,
    ClobPriceHistory,
    ConditionalOrder,
    CopyConfig,
    Market,
    MarketplaceListing,
    MarketplaceSeller,
    MarketplaceStrategy,
    MidpointInfo,
    NewsArticle,
    NewsSignal,
    Order,
    OrderBook,
    OrderBookLevel,
    OrderStatus,
    PaginatedResponse,
    PlaceOrderResponse,
    PolymarketActivity,
    PolymarketEarningsEntry,
    PolymarketPortfolioEntry,
    Portfolio,
    PortfolioPnl,
    Position,
    PriceHistoryEntry,
    RiskSettings,
    SpreadInfo,
    Strategy,
    StrategyBlock,
    StrategyEvent,
    StrategyExecMode,
    StrategyStatusResponse,
    StrategyTemplate,
    StrategyVisibility,
    TickSizeInfo,
    Token,
    TopTraderEntry,
    TraderScore,
    WatchlistItem,
    Webhook,
    WebhookTestResult,
    WhaleTrade,
)

__all__ = [
    # Clients
    "PolyforgeClient",
    "AsyncPolyforgeClient",
    # Errors
    "PolyforgeError",
    "AuthenticationError",
    "PermissionError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    # Enums
    "OrderStatus",
    "StrategyVisibility",
    "StrategyExecMode",
    # Models
    "AiQueryResponse",
    "Alert",
    "Badge",
    "BatchOrderItem",
    "BatchOrderResult",
    "BulkCancelError",
    "BulkCancelResult",
    "ClobBook",
    "ClobPriceHistory",
    "ConditionalOrder",
    "CopyConfig",
    "Market",
    "MarketplaceListing",
    "MarketplaceSeller",
    "MarketplaceStrategy",
    "MidpointInfo",
    "NewsArticle",
    "NewsSignal",
    "Order",
    "OrderBook",
    "OrderBookLevel",
    "PaginatedResponse",
    "PlaceOrderResponse",
    "PolymarketActivity",
    "PolymarketEarningsEntry",
    "PolymarketPortfolioEntry",
    "Portfolio",
    "PortfolioPnl",
    "Position",
    "PriceHistoryEntry",
    "RiskSettings",
    "SpreadInfo",
    "Strategy",
    "StrategyBlock",
    "StrategyEvent",
    "StrategyStatusResponse",
    "StrategyTemplate",
    "TickSizeInfo",
    "Token",
    "TopTraderEntry",
    "TraderScore",
    "WatchlistItem",
    "Webhook",
    "WebhookTestResult",
    "WhaleTrade",
]

__version__ = "1.0.0"
