"""Polyforge Python SDK — typed REST client for the Polyforge trading platform."""

from polyforge.client import AsyncPolyforgeClient, PolyforgeClient
from polyforge.errors import (
    AuthenticationError,
    NotFoundError,
    PermissionError,
    PolyforgeError,
    RateLimitError,
    ServerError,
)
from polyforge.models import (
    AiQueryResponse,
    Alert,
    ClobBook,
    ClobBookLevel,
    ConditionalOrder,
    CopyConfig,
    Market,
    MarketplaceListing,
    MarketplaceSeller,
    MarketplaceStrategy,
    NewsArticle,
    NewsSignal,
    Order,
    OrderBook,
    OrderBookLevel,
    OrderStatus,
    PaginatedResponse,
    PlaceOrderResponse,
    Portfolio,
    PortfolioPnl,
    Position,
    PriceHistoryEntry,
    RiskSettings,
    Strategy,
    StrategyBlock,
    StrategyEvent,
    StrategyExecMode,
    StrategyStatusResponse,
    StrategyTemplate,
    StrategyVisibility,
    Token,
    TopTrader,
    TraderBadge,
    TraderScore,
    WatchlistItem,
    Webhook,
    WebhookTestResult,
    WhaleTrade,
)

__all__ = [
    # Clients
    "PolyforgeClient",
    "AsyncPolyforgeClient",
    # Errors
    "PolyforgeError",
    "AuthenticationError",
    "PermissionError",
    "NotFoundError",
    "RateLimitError",
    "ServerError",
    # Enums
    "OrderStatus",
    "StrategyVisibility",
    "StrategyExecMode",
    # Models
    "AiQueryResponse",
    "Alert",
    "ClobBook",
    "ClobBookLevel",
    "ConditionalOrder",
    "CopyConfig",
    "Market",
    "MarketplaceListing",
    "MarketplaceSeller",
    "MarketplaceStrategy",
    "NewsArticle",
    "NewsSignal",
    "Order",
    "OrderBook",
    "OrderBookLevel",
    "PaginatedResponse",
    "PlaceOrderResponse",
    "Portfolio",
    "PortfolioPnl",
    "Position",
    "PriceHistoryEntry",
    "RiskSettings",
    "Strategy",
    "StrategyBlock",
    "StrategyEvent",
    "StrategyStatusResponse",
    "StrategyTemplate",
    "Token",
    "TopTrader",
    "TraderBadge",
    "TraderScore",
    "WatchlistItem",
    "Webhook",
    "WebhookTestResult",
    "WhaleTrade",
]

__version__ = "1.0.0"
